name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/JoyCoin_WebSite
            git pull origin main
            cd deploy
            sudo docker compose -f docker-compose.prod.yml build --no-cache web
            sudo NEXT_PUBLIC_API_BASE_URL=https://joycoinweb.com/api docker compose -f docker-compose.prod.yml build --no-cache frontend
            sudo docker compose -f docker-compose.prod.yml up -d
